### ISSUE TITLE
Set up website

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface_site#1]
## TODO:

  * [x] 1. Move project to the `surface-ui` org
  * [x] 2. Add sections about the new testing API and hooks (docs)
  * [ ] 3. Review components without examples and see if it should add at least one
  * [ ] 4. Rewiew docs
  * [x] 5. Set up deploy and publish to `Gigalixir`
  * [x] 6. Set up `surface-ui.org` domain
  * [x] 7. Move `surface` to the `surface-ui` org
  * [x] 8. Update Surface to the latest stable version
  * [x] 9. Make `surface_site` public

@lnr0626, @olivermt, @Malian, @miguel-s and @paulstatezny. Since you implemented some of the components we have, feel free to add examples, review the docs or help me with any of the other items you might like. Also, in case you remember anything else, feel free to add more items to the list.

Cheers.

**Comment by msaraiva** [comment]
The website can now be accessed at http://surface-ui.org/

I still need to set up `https` properly.
